In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

In [4]:
# Data manipulation and Data Analysis :
# defination :
'''
1. Changing, organizing, preparing data, info of data, describe the data that makes its easier to understand and useful.

2. Goals : To clean, transform or processing and structure raw data for better usability in differnt ways and scenaios of particular dataset.

Creator :
        Pandas was created by Wes McKinney, a data scientist and software developer who craeated Pandas in 2008 while working at AQR Capital management.
and he works primarilly on these three things one is data aggregation, data manipulation and data analysis.

What is Pandas ???
  
  Pandas is a popular python library used and designed for data manipulation(cleaning, error finding, detecting missing values, transforming and
  structuring raw data) and then secondly Data Analysis that includes finding patterns, insights, fetching details and trends.
  So its simply works with structured(relational) datasets like tables, other structured datasets like spreadsheets like excelsheets or CSV(comma
  seperated files) and semi-structured data like JSON or XML data and time series data.
  
Key Pandas concepts :

1. Series :
           A series is a one dimensional labled array that can hold any data type: integers, floats, strings, or even any python objects.
           Every element in a series has a uniques labled called index.
      ->   Its mostly used to track changes or patterns over time such as temperature, financial data in companies, stocks prices in stock market
           or sales revenue.

2. Data Frame :
           A dataframe is a to dimensional labled data structure in pandas similar to Excel spreadsheet, table in SQL.
           Its consists of rows and columns.
           Wheres rows have indices(lables).
           Whreres columns have names(lables).
           '''
           
# Read data from CSV file and then load it into dataframe variable or object 'df' :

df = pd.read_csv('Data_sources&Data_sets/customer.csv')
 
df

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,44,M,3,Graduate,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5
10104,827703258,48,M,3,Unknown,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3
10105,827712108,47,M,4,Graduate,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3
10106,827888433,42,F,3,Graduate,Married,TX,91750,no,no,no,cellular,White-collar,21390,4
10107,827890758,47,M,4,High School,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4

In [5]:
df = pd.read_excel("Data_sources&Data_sets/SampleSuperstore.xls") # You can also used different encoding schemes if data is not displayed as excel(xlsx) or 
# CSV(comma seperated file) like utf-8 or Latin1

df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [6]:
# Read the file that is in JSON format :

df = pd.read_json('Data_sources&Data_sets/sample_Data.json')

df

,id,name,description,price,category,image
0,1,Apple iPhone 12,The Apple iPhone 12 features a 6.1-inch Super ...,999.00,Electronics,https://www.apple.com/newsroom/images/product/...
1,2,Samsung Galaxy S21,The Samsung Galaxy S21 features a 6.2-inch Dyn...,799.00,Electronics,https://images.samsung.com/is/image/samsung/p6...
2,3,Sony PlayStation 5,The Sony PlayStation 5 features an AMD Zen 2-b...,499.99,Electronics,https://www.sony.com/image/44baa604124b770c824...
3,4,LG OLED55CXPUA 55-inch 4K OLED TV,The LG OLED55CXPUA 55-inch 4K OLED TV features...,1599.99,Electronics,https://www.lg.com/us/images/tvs/md07501804/ga...
4,5,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...
5,6,Fitbit Versa 3 Smartwatch,The Fitbit Versa 3 Smartwatch features a built...,229.95,Electronics,https://www.fitbit.com/global/content/dam/fitb...
6,7,KitchenAid Stand Mixer,The KitchenAid Stand Mixer features a 5-quart ...,399.99,Home & Kitchen,https://www.kitchenaid.com/content/dam/global/...
7,8,Dyson V11 Absolute Cordless Vacuum,The Dyson V11 Absolute Cordless Vacuum feature...,699.99,Home Appliances,https://www.dysoncanada.ca/dam/dyson/images/pr...
8,9,Ninja Foodi Smart XL Grill,The Ninja Foodi Smart XL Grill features 6-in-1...,279.99,Home & Kitchen,https://www.ninjakitchen.com/medias/Ninja-OP50...
9,10,Canon EOS Rebel T8i DSLR Camera,The Canon EOS Rebel T8i DSLR Camera features a...,899.00,Electronics,https://www.canon.com.au/-/media/images/produc...
10,11,Apple AirPods Pro,The Apple AirPods Pro feature active noise can...,249.00,Electronics,https://www.apple.com/v/airpods-pro/b/images/m...
11,12,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...
12,13,Fitbit Charge 4 Fitness Tracker,The Fitbit Charge 4 Fitness Tracker features G...,129.95,Electronics,https://www.fitbit.com/global/content/dam/fitb...
13,14,Samsung Galaxy Watch3,The Samsung Galaxy Watch3 features a rotating ...,399.99,Electronics,https://images.samsung.com/is/image/samsung/as...
14,15,Sony WH-1000XM4 Wireless Noise-Cancelling Head...,The Sony WH-1000XM4 Wireless Noise-Cancelling ...,349.99,Electronics,https://www.sony.com/image/1cdd6354c4cd21cc4f7...
15,16,Breville Barista Express Espresso Machine,The Breville Barista Express Espresso Machine ...,699.95,Home & Kitchen,https://www.breville.com/content/dam/breville/...
16,17,Keurig K-Elite Coffee Maker,The Keurig K-Elite Coffee Maker features a str...,169.99,Home & Kitchen,https://www.keurig.com/content/dam/global-ecom...
17,18,iRobot Roomba i7+ Robot Vacuum,The iRobot Roomba i7+ Robot Vacuum features au...,799.99,Home & Kitchen,https://store.irobot.com/default/i7-vacuuming-...
18,19,Ninja Foodi Digital Air Fry Oven,The Ninja Foodi Digital Air Fry Oven features ...,209.99,Home & Kitchen,https://www.ninjakitchen.com/static/img/produc...
19,20,Cuisinart ICE-70 Ice Cream Maker,The Cuisinart ICE-70 Ice Cream Maker features ...,139.99,Home & Kitchen,https://www.cuisinart.com/share/images/product...

In [11]:
# Also gcsfs library used to read data from paticular cloud storage like Google Cloud.

# You can also create new dataframes(data sets) by using dictionaries :

Data = {
    'Name' : ['Ahmad', 'Rehan', 'Faizan'],
    'Age' : [23, 24, 22],
    'Job' : ['Senior Data Scientist and Machine Learning Expert', 'Product Manager', 'Marketing Manager'],
    'Company' : ['Google', 'Microsoft', 'Nvidia']
}

df2 = pd.DataFrame(Data)

df2

     Name  Age                                                Job    Company
0   Ahmad   23  Senior Data Scientist and Machine Learning Expert     Google
1   Rehan   24                                    Product Manager  Microsoft
2  Faizan   22                                  Marketing Manager     Nvidia

In [12]:
# Then convert this dataframe into CSV file by using to_csv() function :

df2.to_csv('Data_sources&Data_sets/Employees_data.csv', index=False)
df2

     Name  Age                                                Job    Company
0   Ahmad   23  Senior Data Scientist and Machine Learning Expert     Google
1   Rehan   24                                    Product Manager  Microsoft
2  Faizan   22                                  Marketing Manager     Nvidia

In [14]:
# Then convert this dataFrame df2 into Excel format file (like xls or xlsx) :

df2.to_excel('Data_sources&Data_sets/Employees_dataset.xlsx', index=False)
df2

     Name  Age                                                Job    Company
0   Ahmad   23  Senior Data Scientist and Machine Learning Expert     Google
1   Rehan   24                                    Product Manager  Microsoft
2  Faizan   22                                  Marketing Manager     Nvidia

In [16]:
# Then now convert this dataframe df2 into .JSON format.

df2.to_json('Data_sources&Data_sets/Employees_info.json')

df2

     Name  Age                                                Job    Company
0   Ahmad   23  Senior Data Scientist and Machine Learning Expert     Google
1   Rehan   24                                    Product Manager  Microsoft
2  Faizan   22                                  Marketing Manager     Nvidia